Update wapiti_scan.yaml

diff --git a/.github/workflows/wapiti_scan.yaml b/.github/workflows/wapiti_scan.yaml
--- a/.github/workflows/wapiti_scan.yaml
+++ b/.github/workflows/wapiti_scan.yaml
@@ -1,5 +1,3 @@
-name: Wapiti Scan
-
 on:
   push:
     branches:
@@ -11,9 +9,24 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v2
 
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: 3.10
+
+      - name: Install Wapiti
+        run: pip install wapiti
+
+      - name: Run Wapiti Scan
+        run: |
+          wapiti -u https://online-shop-php.000webhostapp.com/index.php || true
+          # Using "|| true" to continue execution even if the Wapiti command fails
+
+      - name: Upload scan report as artifact
+        if: success()
+        uses: actions/upload-artifact@v2
+        with:
+          name: wapiti-report.txt
+          path: wapiti-report.txt
